### ISSUE TITLE
Transfer one collection field to other collection

### ISSUE THREAD

**Issue by YaqoobAhmed** [YaqoobAhmed/BIrdsApp#2]
i want to set user collection phone# into my other collections without filling the contact textfield again

**Comment by KhubaibJamal** [comment]
Hey [@YaqoobAhmed  ](https://github.com/YaqoobaAhmed), I am working on this issue, assign me.

**Comment by KhubaibJamal** [comment]
Hey @YaqoobAhmed I solved your phone number problem.
